server:
  port: ${SERVER_PORT:8082}
spring:
  application:
    name: ${SERVICE_NAME:core_service}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL:jdbc:postgresql://ep-withered-fire-a11eu7k1-pooler.ap-southeast-1.aws.neon.tech/core_service?sslmode=require&channel_binding=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_n17wVeFxpgYH}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: ${SPRING_LIQUIBASE_CHANGE_LOG:classpath:db/changelog/db.changelog-master.yaml}
  jpa:
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
jwt:
  secret: ${JWT_SECRET:VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBmb3IgSldU}
  expiration:
    ms: ${JWT_EXPIRATION_MS:900000}
auth-service:
  base-url: ${AUTH_SERVICE_BASE_URL:http://localhost:8081/}
user-service:
  base-url: ${USER_SERVICE_BASE_URL:http://localhost:8080/}
